raise log level to info for ecal_pn validation sample
this is necessary since the Tracking module produces enough extra debug
messages that pushes the log over the 100MB limit set by GitHub for
files within a git working tree.

This was originally seen when attempting to open a PR for the newly
generated gold ov v4.0.3 within the GitHub workflows.

  remote: error: Trace: 6a310c1456671eedcc7c0152b13d263de0924c62a64eb0ad3ace7ce2730ba02a
  remote: error: See https://gh.io/lfs for more information.
  remote: error: File .github/validation_samples/ecal_pn/gold.log is 635.06 MB; this exceeds GitHub's file size limit of 100.00 MB
  remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
  To https://github.com/LDMX-Software/ldmx-sw
   ! [remote rejected] new-gold-v4.0.3 -> new-gold-v4.0.3 (pre-receive hook declined)
  error: failed to push some refs to 'https://github.com/LDMX-Software/ldmx-sw'
  Error: The process '/usr/bin/git' failed with exit code 1

Instead of attempting to figure out git lfs, I am just requiring there
to be less printouts.